site_name: Django REST - Access Policy

theme:
  name: "material"
  language: en
  feature:
    tabs: false
  palette:
    primary: black
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/security

repo_name: rsinger86/drf-access-policy
repo_url: https://github.com/rsinger86/drf-access-policy

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji

nav:
  - Intro: index.md
  - Usage - ViewSets: usage/view_set_usage.md
  - Usage - Function-Based Views: usage/function_based_view_usage.md
  - Statement Elements: statement_elements.md
  - Statement Dataclasses: statement_dataclasses.md
  - Policy Evaluation Logic: policy_logic.md
  - Custom/Object-Level Conditions: object_level_permissions.md
  - Field-Level Permissions: field_level_permissions.md
  - ViewSet Mixin: view_set_mixin.md
  - Reuse Conditions/Permissions: reusable_conditions.md
  - Loading External Statements: loading_external_source.md
  - Multitenancy/Scoping QuerySets: multi_tenacy.md
  - Policy Re-Use: policy_reuse.md
  - Customizing: customization.md
  - Migrating: migration_notes.md
  - License: license.md
